platform :ios, '10.0'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Download' do
use_frameworks!

install_all_flutter_pods(flutter_application_path)

pod 'Cache'
pod 'MJRefresh'
pod 'SnapKit'
pod 'Bugly'
pod 'Floaty', '~> 4.2.0'
pod "GSImageViewerController"
pod 'Swifter', '~> 1.4.7'
pod 'Alamofire', '~> 5.2'
pod "PromiseKit", "~> 6.8"

end
