platform :ios, '10.0'

target 'Download' do
use_frameworks!

pod 'Cache'
pod 'MJRefresh'
pod 'SnapKit'
pod 'Bugly'
pod 'Floaty', '~> 4.2.0'
pod "GSImageViewerController"
pod 'Swifter', '~> 1.4.7'
pod 'Alamofire', '~> 5.2'

end
