name: Swift

on:
  push:
    branches: [ SDK ]
  pull_request:
    branches: [ SDK ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Download; swift build -v
    - name: Run tests
      run: swift test -v